use chrono::{DateTime, NaiveDate, Utc};
use rocket::form::FromForm;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use utoipa::{IntoParams, ToSchema};
use uuid::Uuid;

use crate::models::transaction::TransactionType;

#[derive(Debug, Deserialize, ToSchema)]
pub struct CreateTransactionRequest {
    /// Optional account id. When omitted, the first cash account is used.
    pub account_id: Option<Uuid>,
    /// Positive amount in the account currency.
    pub amount: Decimal,
    /// Transaction kind. Use the transfers endpoints for transfer creation.
    pub r#type: TransactionType,
    /// Category label.
    pub category: String,
    /// Optional free-form note.
    pub note: Option<String>,
    /// Booking date in `YYYY-MM-DD` format.
    pub date: NaiveDate,
}

#[derive(Debug, Deserialize, ToSchema)]
pub struct UpdateTransactionRequest {
    /// Optional account id. When omitted, the first cash account is used.
    pub account_id: Option<Uuid>,
    /// Positive amount in the account currency.
    pub amount: Decimal,
    /// Transaction kind. Use the transfers endpoints for transfer creation.
    pub r#type: TransactionType,
    /// Category label.
    pub category: String,
    /// Optional free-form note.
    pub note: Option<String>,
    /// Booking date in `YYYY-MM-DD` format.
    pub date: NaiveDate,
}

#[derive(Debug, Clone, Default, FromForm, IntoParams)]
#[into_params(parameter_in = Query)]
pub struct TransactionFilters {
    /// Filter by `income`, `expense`, or `transfer`.
    pub r#type: Option<TransactionType>,
    /// Case-insensitive partial category match.
    pub category: Option<String>,
    /// Only return transactions linked to a specific account.
    pub account_id: Option<Uuid>,
    /// Inclusive start date in `YYYY-MM-DD` format.
    pub start_date: Option<String>,
    /// Inclusive end date in `YYYY-MM-DD` format.
    pub end_date: Option<String>,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct TransactionResponse {
    /// Stable unique identifier for the transaction entry.
    pub id: Uuid,
    /// Owning account id when the entry belongs to an account.
    pub account_id: Option<Uuid>,
    /// Account display name at read time.
    pub account_name: Option<String>,
    /// Account currency at read time.
    pub account_currency: Option<String>,
    /// Positive transaction amount in the entry currency.
    pub amount: Decimal,
    /// Stored transaction kind.
    pub r#type: TransactionType,
    /// Display transaction kind, including `transfer` for mirrored transfer entries.
    pub display_type: TransactionType,
    /// Category label.
    pub category: String,
    /// Optional free-form note.
    pub note: Option<String>,
    /// Booking date in `YYYY-MM-DD` format.
    pub date: NaiveDate,
    /// Timestamp when the entry was created.
    pub created_at: DateTime<Utc>,
    /// Transfer id when the entry was generated by a transfer.
    pub transfer_id: Option<Uuid>,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct MonthlySummaryResponse {
    /// First day of the summarized month.
    pub month: NaiveDate,
    /// Total income excluding transfer mirrors.
    pub income_total: Decimal,
    /// Total expense excluding transfer mirrors.
    pub expense_total: Decimal,
    /// `income_total - expense_total`.
    pub net_total: Decimal,
}

#[derive(Debug, Clone, Default, FromForm, IntoParams)]
#[into_params(parameter_in = Query)]
pub struct CategorySummaryQuery {
    /// Month anchor in `YYYY-MM-DD` format. The day portion is normalized to the first of the month.
    pub month: Option<String>,
    /// Summary type. Defaults to `expense`.
    pub r#type: Option<TransactionType>,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct CategorySummaryItem {
    /// Category label.
    pub category: String,
    /// Total amount aggregated for the category.
    pub total: Decimal,
    /// Percentage of the month's grand total.
    pub percentage: f64,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct CategorySummaryResponse {
    /// First day of the summarized month.
    pub month: NaiveDate,
    /// Summary type that was aggregated.
    pub r#type: TransactionType,
    /// Category totals sorted by amount descending.
    pub items: Vec<CategorySummaryItem>,
}
