# Generated by Django 6.0.3 on 2026-03-20 00:48

from django.db import migrations

import minift.apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_auth_fields"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[("objects", minift.apps.users.models.UserManager())],
        ),
    ]
