use rocket::Route;

use crate::handlers;

pub fn all() -> Vec<Route> {
    routes![
        crate::cors::preflight,
        handlers::health::health,
        handlers::integrations::connect,
        handlers::integrations::callback,
        handlers::integrations::disconnect,
        handlers::integrations::google_status,
        handlers::integrations::gmail_status,
        handlers::integrations::sync_now,
        handlers::imports::list,
        handlers::imports::approve,
        handlers::imports::reject,
        handlers::imports::link_account,
        handlers::auth::register,
        handlers::auth::resend_verification,
        handlers::auth::verify_email,
        handlers::auth::login,
        handlers::auth::request_password_reset,
        handlers::auth::confirm_password_reset,
        handlers::auth::request_password_change,
        handlers::auth::confirm_password_change,
        handlers::auth::refresh,
        handlers::auth::logout,
        handlers::auth::me,
        handlers::auth::update_me,
        handlers::accounts::list,
        handlers::accounts::get,
        handlers::accounts::create,
        handlers::accounts::update,
        handlers::accounts::delete,
        handlers::exchange_rates::list,
        handlers::exchange_rates::replace,
        handlers::transactions::list,
        handlers::transactions::get,
        handlers::transactions::create,
        handlers::transactions::update,
        handlers::transactions::delete,
        handlers::transactions::monthly_summary,
        handlers::transactions::category_summary,
        handlers::budgets::list,
        handlers::budgets::get,
        handlers::budgets::create,
        handlers::budgets::update,
        handlers::budgets::delete,
        handlers::transfers::list,
        handlers::transfers::create,
        handlers::transfers::delete,
        handlers::recurring::list,
        handlers::recurring::create,
        handlers::recurring::update,
        handlers::recurring::delete,
    ]
}
